ShopV2/Areas/admin/Controllers/DHController.cs
using ShopV2.Areas.admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopV2.Areas.admin.Controllers
{
    public class DHController : Controller
    {
        AdminContext db = new AdminContext();
        // GET: admin/DH
        public ActionResult Index()
        {
            var model = db.Orders.ToList();
            return View(model);
        }
    }
}

ShopV2/Areas/admin/Views/DH/Index.cshtml
@model IEnumerable<Order>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="btn btn-primary btn-default" href="@Url.Action("Index", "DH")" role="button">Làm mới</a>
            <div class="form-group input-group navbar-right">
                @using (Ajax.BeginForm("Index", "DH", new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "Get" }))
                {
                    <input type="search" name="name" class="form-control" style="width:300px" placeholder="Nhập số điện thoại khách hàng..." />
                    <button class="btn btn-success" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                }
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive table-bordered">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Mã Đơn Hàng  </th>
                            <th>Số Điện Thoại</th>
                            <th>Tin Nhắn</th>
                            <th>Thời Gian</th>
                            <th>Tình Trạng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{int i = 0;}
                        @foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <td>@i</td>
                                <td>@Html.DisplayFor(modelItem => item.orderID)</td>
                                <td>@Html.DisplayFor(modelItem => item.cusPhone)</td>
                                <td>@Html.DisplayFor(modelItem => item.orderMessage)</td>
                                <td>@Html.DisplayFor(modelItem => item.orderDateTime)</td>
                                <td>
                                    @if (item.orderStatus.Equals("0"))
                                    {
                                        <p>Chưa Thanh Toán</p>

                                    }
                                    else
                                    {
                                        <p>Đã Thanh Toán</p>
                                    }
                                </td>



                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>