ShopV2/Controllers/CTDHController.cs
using ShopV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopV2.Controllers
{
    public class CTDHController : Controller
    {
        UserContext db = new UserContext();
        // GET: CTDH
        public ActionResult Index(String id) 

        {
            var model = db.OrderDetails.Where(m => m.orderID == id).ToList();
            return View(model);
        }
    }
}

ShopV2/Controllers/QuanLyDonHangController.cs
using ShopV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopV2.Controllers
{
    public class QuanLyDonHangController : Controller
    {
        UserContext db = new UserContext();
        // GET: QuanLyDonHang
        public ActionResult Index(String id)
        {
            var model = db.Orders.Where(m => m.cusPhone == id).ToList();
            return View(model);
        }

        public ActionResult Update (String id)
        {
            var model = db.Orders.Where(m => m.orderID == id).SingleOrDefault();
            model.orderStatus = "1";
            db.SaveChanges();
            return RedirectToAction("Index", "QuanLyDonHang");
        }


    }
}

ShopV2/Views/QuanLyDonHang/Index.cshtml
@model IEnumerable<ShopV2.Models.Order>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutShop.cshtml";
}

<div class="panel-body">
    <div class="table-responsive table-bordered">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Mã Đơn Hàng  </th>
                    <th>Tin Nhắn</th>
                    <th>Thời Gian</th> 
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 0;}
                @foreach (var item in Model)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@Html.DisplayFor(modelItem => item.orderID)</td>
                        <td>@Html.DisplayFor(modelItem => item.orderMessage)</td>
                        <td>@Html.DisplayFor(modelItem => item.orderDateTime)</td>
                        <td>
                        <td>
                            @if (item.orderStatus.Equals("0")) {
                            <a href="@Url.Action("Index", "CTDH", new { id = item.orderID })">Detail</a>
                            <a href="@Url.Action("Update", "QuanLyDonHang", new { id = item.orderID })">Xác nhận</a>
                            } 
                            else {
                            <a href="@Url.Action("Index", "CTDH", new { id = item.orderID })">Detail</a>
                            <button> Đã Thanh Toán</button>
                            }
                            
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.table-responsive -->
</div>

ShopV2/Views/QuanLyDonHang/test.cshtml
@model  IEnumerable<ShopV2.Models.Order>
@{
    ViewBag.Title = "test";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@foreach (var item in Model)
{
    @item.orderID;
}